-- -------------------------------------------------------------
-- 
-- File Name: Q:\Users\Qlab\Documents\Blake\iirfilter\hdlsrc\polyphaseIIR\DecimCommutator.vhd
-- Created: 2014-05-12 13:26:15
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DecimCommutator
-- Source Path: polyphaseIIR/IIRDecimFilter/Stage1/DecimCommutator
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DecimCommutator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_2_1                         :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        input                             :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        output1                           :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        output2                           :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
        );
END DecimCommutator;


ARCHITECTURE rtl OF DecimCommutator IS

  -- Signals
  SIGNAL input_signed                     : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL downsamp1_out1                   : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL delay2_out1                      : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL delay1_out1                      : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL downsamp2_out1                   : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL delay3_out1                      : signed(11 DOWNTO 0);  -- sfix12_En11

BEGIN
  input_signed <= signed(input);

  -- Downsample by 2 register (Sample offset 0)
  downsamp1_output_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        downsamp1_out1 <= to_signed(2#000000000000#, 12);
      ELSIF enb_1_2_1 = '1' THEN
        downsamp1_out1 <= input_signed;
      END IF;
    END IF;
  END PROCESS downsamp1_output_process;


  delay2_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        delay2_out1 <= to_signed(2#000000000000#, 12);
      ELSIF enb_1_2_0 = '1' THEN
        delay2_out1 <= downsamp1_out1;
      END IF;
    END IF;
  END PROCESS delay2_process;


  output1 <= std_logic_vector(delay2_out1);

  delay1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        delay1_out1 <= to_signed(2#000000000000#, 12);
      ELSIF enb = '1' THEN
        delay1_out1 <= input_signed;
      END IF;
    END IF;
  END PROCESS delay1_process;


  -- Downsample by 2 register (Sample offset 0)
  downsamp2_output_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        downsamp2_out1 <= to_signed(2#000000000000#, 12);
      ELSIF enb_1_2_1 = '1' THEN
        downsamp2_out1 <= delay1_out1;
      END IF;
    END IF;
  END PROCESS downsamp2_output_process;


  delay3_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        delay3_out1 <= to_signed(2#000000000000#, 12);
      ELSIF enb_1_2_0 = '1' THEN
        delay3_out1 <= downsamp2_out1;
      END IF;
    END IF;
  END PROCESS delay3_process;


  output2 <= std_logic_vector(delay3_out1);

END rtl;

