-- -------------------------------------------------------------
-- 
-- File Name: Q:\Users\Qlab\Documents\Blake\iirfilter\hdlsrc\polyphaseIIR\Stage2.vhd
-- Created: 2014-05-12 13:26:15
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Stage2
-- Source Path: polyphaseIIR/IIRDecimFilter/Stage2
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Stage2 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2_0                         :   IN    std_logic;
        enb_1_4_1                         :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        Input                             :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En11
        Output                            :   OUT   std_logic_vector(14 DOWNTO 0)  -- sfix15_En11
        );
END Stage2;


ARCHITECTURE rtl OF Stage2 IS

  -- Component Declarations
  COMPONENT DecimCommutator_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2_0                       :   IN    std_logic;
          enb_1_4_1                       :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          input                           :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En11
          output1                         :   OUT   std_logic_vector(13 DOWNTO 0);  -- sfix14_En11
          output2                         :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En11
          );
  END COMPONENT;

  COMPONENT Phase1_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          Input                           :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En11
          output                          :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En11
          );
  END COMPONENT;

  COMPONENT Phase2_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          Input                           :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En11
          output                          :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En11
          );
  END COMPONENT;

  -- Signals
  SIGNAL Input_signed                     : signed(13 DOWNTO 0);  -- sfix14_En11
  SIGNAL Input_1                          : signed(13 DOWNTO 0);  -- sfix14_En11
  SIGNAL DecimCommutator_out1             : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL DecimCommutator_out2             : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL Phase1_out1                      : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL Phase1_out1_signed               : signed(13 DOWNTO 0);  -- sfix14_En11
  SIGNAL Phase1_out1_buff                 : signed(13 DOWNTO 0);  -- sfix14_En11
  SIGNAL Phase2_out1                      : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL Phase2_out1_signed               : signed(13 DOWNTO 0);  -- sfix14_En11
  SIGNAL Phase2_out1_buff                 : signed(13 DOWNTO 0);  -- sfix14_En11
  SIGNAL Sum1_out1                        : signed(14 DOWNTO 0);  -- sfix15_En11
  SIGNAL Gain_cast                        : signed(29 DOWNTO 0);  -- sfix30_En22
  SIGNAL delay6_out1                      : signed(14 DOWNTO 0);  -- sfix15_En11

BEGIN
  u_DecimCommutator : DecimCommutator_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2_0 => enb_1_2_0,
              enb_1_4_1 => enb_1_4_1,
              enb_1_4_0 => enb_1_4_0,
              input => std_logic_vector(Input_1),  -- sfix14_En11
              output1 => DecimCommutator_out1,  -- sfix14_En11
              output2 => DecimCommutator_out2  -- sfix14_En11
              );

  u_Phase1 : Phase1_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              Input => DecimCommutator_out1,  -- sfix14_En11
              output => Phase1_out1  -- sfix14_En11
              );

  u_Phase2 : Phase2_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              Input => DecimCommutator_out2,  -- sfix14_En11
              output => Phase2_out1  -- sfix14_En11
              );

  Input_signed <= signed(Input);

  in_0_pipe_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Input_1 <= to_signed(2#00000000000000#, 14);
      ELSIF enb_1_2_0 = '1' THEN
        Input_1 <= Input_signed;
      END IF;
    END IF;
  END PROCESS in_0_pipe_process;


  Phase1_out1_signed <= signed(Phase1_out1);

  cd_0_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Phase1_out1_buff <= to_signed(2#00000000000000#, 14);
      ELSIF enb_1_4_0 = '1' THEN
        Phase1_out1_buff <= Phase1_out1_signed;
      END IF;
    END IF;
  END PROCESS cd_0_process;


  Phase2_out1_signed <= signed(Phase2_out1);

  cd_1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF reset = '1' THEN
        Phase2_out1_buff <= to_signed(2#00000000000000#, 14);
      ELSIF enb_1_4_0 = '1' THEN
        Phase2_out1_buff <= Phase2_out1_signed;
      END IF;
    END IF;
  END PROCESS cd_1_process;


  Sum1_out1 <= (resize(Phase1_out1_buff, 15)) + (resize(Phase2_out1_buff, 15));

  Gain_cast <= resize(Sum1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  delay6_out1 <= Gain_cast(25 DOWNTO 11);

  Output <= std_logic_vector(delay6_out1);

END rtl;

